version: "3"
services:
  postgresql:
    container_name: poss
    image: my-postgres
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_POSTGRES_PASSWORD=postgres_pass
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pg_partman_bgw
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator
    volumes:
      - poss:/bitnami/postgresql
      - dann:/opt
    ports:
      - "5432:5432"
  redis:
    container_name: poss-redis
    image: bitnami/redis:latest
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=redis_password
    ports:
      - "6379:6379"
    volumes:
      - poss-red:/bitnami/redis/data
volumes:
  poss:
  dann:
  poss-red:
